language: minimal

install:
  - curl -sSL https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.9.0/ct-v0.9.0-x86_64-unknown-linux-gnu > ct
  - chmod +x ct

script:
  - ./ct --files-dir rootfs < config.yml > config.ign
